sudo: false
language: java
jdk: oraclejdk7
cache:
  directories:
  - "$HOME/.m2/repository"
before_script:
- git config --global user.name rmpestano
- git config --global user.email rmpestano@gmail.com
script:
- mvn clean package -Pdocs
- mvn -q scm-publish:publish-scm -Pdocs
env:
  global:
  - secure: hIl7unZCLDXPjmyNLO+GNzOXqSY19FmJSPWLw4iHFpVZ4cLFC0QiZXfqdW/VPG0uWUfPUFTIUeJIa4ezAu8vPHzjot7xc5VfifhBWA8MXTZg9tzz6jjhvaH8NTrv+FZdBcRoGYLxHUK2ORABJ3Vzxt9JODkSpDPUWe8YgF4ufoyVROuHP0+aTMwVrFu4Ux4+JRGuI5cLMUg1YhrKwJHSzcRK3rtgQ1/WNvWrUOuVNZ+wbOiLqVif4CwET3tLps52n6UnNcYibqQDkGhrdMJ4vKsgBkkJXY8lYJZChuy63/QgZK9dKGoWU4LBPdw5MLhvbflvAAT0Jsl5giQyISMwPsM+aTNTJLlI4W3WaMaMOYi//hmmo/dCWu4fbDHOTCBNrPMiq4eQMuBpY10zAwmoVp8ymyzRLUpU5/5SN7rlt2BaKCIO2HOMVZQzSjwBwjDH62QnPMuRZjI05Vtu3UnvEDTfpDmdi9ca4VGKgyNUtNpEf6vnDhxkHZEzIUXvRWsb8JIVisVKN1KapykgF+mKOTGpvEviV3yCb8koeh38R+tdYWf9H7ivzBTRCuFKqMSZqK13w2uLEuGo13/AYNmhS2FCLi1qxoWcieffn1IsibTYDkidtYZbZZK5NsMDkTCY9uW+YuQ5y1AnUWL9DR90CRDcf4h0efyPgHt555K+7Ao=
  - secure: Q0mi+dOsoJR+Z0FuDilqW0aL+2nDDouMmlKVGJzQd2tCE0027jLFFwG4l9I3EsSi4DlO1wPTckio7suWfsMhtYsppsscRUKA1kGbm1CfPA8eB0VEJyIYA2Nd0YIsQiHHazauybg7Da5Y9HO6q84Q8nuGT7kokf4BsQY0ziD8ODHCh3DKTG/BKJ1B7AKeJuBWaWZVuUZDbG/Fklbte7rXzYLmPLs9XjtmYFXT+ArNJh/J1J047o1Yp4Ju5mSppGDoF01JGbFa4R/FEfOfzbo0KwvcDYK2t0r57tRD9o26XAiH+VVjbmxQAcvFi6Kn2BiBNAkFZaGdTq893FWy0801IQqRvHl/39m3bcmPzG420Xjljf8IInnGvpbctRWD2xH653tXsuUm6u0qys35BxXs8nFS8NdXQtqD5XkTW46ho1+EaHggAyh26nd9ac3gerrRXLTcG1LNixneJnZZNbXYYcmTGvLkIkeXGcgx2ne2vP++Tgoi3idN/iig+WzbuDDWJgFbX+2wGQ8rsN0fXktvr0EsVbhZjwS6t2SOo9KWQ4IHiBxdBVzFHbS8lcZqoBMvGMcMOPQ3b9fYQGK4yRpAHCqYtN0y5b28GoiF/9O6LTgFMxWGJjmOsU3C2blqocA0OeJwTr5Qc546f5QQIGCp8TLK3Qo3h37NgDoBlQiWctM=
